# NumPy Interview Questions & Answers (30)


## 1. What is NumPy?
**NumPy** (Numerical Python) is the core Python library for numerical and scientific computing. It provides:
- The `ndarray` object — a fast, memory-efficient multi-dimensional array
- Vectorized mathematical operations (no explicit Python loops needed)
- Tools for linear algebra, Fourier transforms, and random number generation
- The foundation on which pandas, scikit-learn, TensorFlow, PyTorch, etc. are built

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


## 2. Why is NumPy faster than Python lists?
- **Contiguous memory**: NumPy arrays store elements of the same dtype in one contiguous block, while Python lists store pointers to scattered objects.
- **Fixed data type**: No per-element type checking at runtime.
- **Vectorized C loops**: Operations are implemented in compiled C and use SIMD instructions, avoiding Python's interpreter overhead.
- **No boxing/unboxing**: Python list elements are full Python objects (with overhead); NumPy stores raw values.

## 3. What is an ndarray in NumPy?
`ndarray` (N-dimensional array) is NumPy's core data structure — a grid of values, all of the **same data type**, indexed by a tuple of non-negative integers. It has attributes like `shape`, `dtype`, `ndim`, `size`, and `strides` that describe its structure in memory.

## 4. What is the difference between a Python list and a NumPy array?
| Feature | Python List | NumPy Array |
|---|---|---|
| Data type | Can hold mixed types | Homogeneous (single dtype) |
| Memory | Higher (stores object pointers) | Lower (contiguous fixed-size blocks) |
| Speed | Slower for numeric ops | Much faster (vectorized, C-level) |
| Operations | No built-in element-wise math | Supports vectorized math, broadcasting |
| Size | Dynamic, resizable | Fixed size once created |
| Functionality | General-purpose container | Rich numerical/linear algebra API |

## 5. How do you create a NumPy array?
Common ways: from a Python list/tuple, or using built-in creation functions.

In [7]:
a = np.array([1, 2, 3])                     # from a list
b = np.array([(1, 2), (3, 4)])              # from a list of tuples (2D)
c = np.zeros((2, 3))                        # array of zeros
d = np.ones((2, 3))                         # array of ones
e = np.full((2, 2), 7)                      # constant value
f = np.eye(3)                                # identity matrix
g = np.arange(0, 10, 2)                     # range with step
h = np.linspace(0, 1, 5)                    # evenly spaced values
i = np.random.rand(2, 2)                    # random values [0,1)
print(a, b, c, d, e, f, g, h, i, sep='\n')

[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.41934676 0.44248556]
 [0.73732958 0.24404886]]


## 6. Difference between np.arange() and np.linspace()?

| Feature | `arange()` | `linspace()` |
|---|---|---|
| Defined by | step size | number of points |
| Syntax | `arange(start, stop, step)` | `linspace(start, stop, num)` |
| Endpoint | excluded by default | included by default |
| Use case | known step size | known number of points needed |

## 7. What are the different ways to initialize arrays in NumPy?
- `np.array()` — from existing data
- `np.zeros()`, `np.ones()`, `np.full()` — constant-value arrays
- `np.empty()` — uninitialized array (fast, garbage values)
- `np.eye()` / `np.identity()` — identity matrix
- `np.arange()`, `np.linspace()`, `np.logspace()` — sequences
- `np.random.rand()`, `np.random.randn()`, `np.random.randint()` — random arrays
- `np.zeros_like()`, `np.ones_like()`, `np.full_like()` — same shape as another array

## 8. How do you check the shape, size, dimensions, and data type of an array?

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:', arr.shape)   # (rows, cols)
print('Size:', arr.size)     # total number of elements
print('Ndim:', arr.ndim)     # number of dimensions
print('Dtype:', arr.dtype)   # data type of elements
print('Itemsize:', arr.itemsize)  # bytes per element

Shape: (2, 3)
Size: 6
Ndim: 2
Dtype: int64
Itemsize: 8


## 9. What are NumPy data types (dtype)?
`dtype` describes the type of each element in an array — e.g. `int32`, `int64`, `float32`, `float64`, `bool`, `complex128`, `object`, `<U10` (unicode string). Unlike Python, NumPy dtypes have a **fixed size in memory**, which is key to performance. You can specify dtype explicitly when creating an array.

In [11]:
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1.5, 2.5], dtype=np.float64)
c = np.array([True, False], dtype=np.bool_)
print(a.dtype, b.dtype, c.dtype)

int32 float64 bool


## 10. How do you change the data type of a NumPy array?
Use `.astype()`, which returns a **new array** with the converted dtype (does not modify in place).

In [12]:
arr = np.array([1.7, 2.3, 3.9])
int_arr = arr.astype(np.int32)   # truncates decimals
print(int_arr, int_arr.dtype)

[1 2 3] int32


## 11. What is array indexing in NumPy?
Indexing lets you access individual elements using integer positions, similar to Python lists, but extended to multiple dimensions using comma-separated indices `arr[row, col]`.

In [13]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr[0, 1])    # 20 -> row 0, col 1
print(arr[-1, -1])  # 60 -> last row, last col

20
60


## 12. What is slicing in NumPy?
Slicing extracts a **sub-array** using `start:stop:step` syntax, extended across dimensions. Slices return a **view** (not a copy) of the original array by default.

In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[0:2, 1:3])   # rows 0-1, cols 1-2
print(arr[:, 0])       # all rows, first column
print(arr[::-1])       # reverse row order

[[2 3]
 [6 7]]
[1 5 9]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


## 13. What is Boolean indexing?
Boolean indexing selects elements using a **boolean array/condition** of the same shape. It's commonly used for filtering data based on a condition.

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(mask)          # [False False False  True  True  True]
print(arr[mask])     # [4 5 6]
print(arr[arr % 2 == 0])  # even numbers -> [2 4 6]

[False False False  True  True  True]
[4 5 6]
[2 4 6]


## 14. What is Fancy indexing?
Fancy indexing means passing an **array (or list) of indices** to select multiple, arbitrary elements at once. Unlike slicing, fancy indexing always returns a **copy**, not a view.

In [16]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])   # [10 30 50]

arr2d = np.array([[1, 2], [3, 4], [5, 6]])
print(arr2d[[0, 2], [1, 0]])  # picks (0,1) and (2,0) -> [2 5]

[10 30 50]
[2 5]


## 15. What is broadcasting in NumPy?
Broadcasting is the mechanism that lets NumPy perform element-wise operations on arrays of **different but compatible shapes** without explicitly copying data — the smaller array is conceptually 'stretched' to match the larger array's shape.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2, 3)
b = np.array([10, 20, 30])              # shape (3,)
print(a + b)   # b is brgoadcast across each row

[[11 22 33]
 [14 25 36]]


## 16. What are the broadcasting rules in NumPy?
Comparing shapes **from right to left**, two dimensions are compatible when:
1. They are **equal**, or
2. One of them is **1** (it gets stretched to match), or
3. One dimension is **missing** (treated as 1)

If none of these hold for any dimension, NumPy raises a `ValueError`.

In [18]:
a = np.ones((3, 4))
b = np.ones((4,))       # shape (4,) broadcasts with (3, 4) -> ok
print((a + b).shape)

c = np.ones((3, 1))
d = np.ones((1, 4))
print((c + d).shape)    # both stretch -> (3, 4)

try:
    e = np.ones((3, 5))
    a + e                # incompatible: 4 vs 5
except ValueError as err:
    print('Error:', err)

(3, 4)
(3, 4)
Error: operands could not be broadcast together with shapes (3,4) (3,5) 


## 17. What is vectorization, and why is it important?
Vectorization means replacing explicit Python `for` loops with array-level (whole-array) operations that run in optimized, compiled C code under the hood. It's important because it:
- Dramatically improves performance
- Produces shorter, more readable code
- Reduces Python interpreter overhead
- Enables use of CPU-level optimizations (SIMD)

In [29]:
arr = np.arange(50)
result = arr ** 2   # vectorized — no explicit loop needed
result

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401])

## 18. What is the difference between reshape() and resize()?

| Feature | `reshape()` | `resize()` |
|---|---|---|
| In place? | No — returns new array/view | Yes — modifies original |
| Element count | Must match original size | Can differ (pads/truncates) |
| Return | New reshaped array | `None` (or new array via `np.resize()`) |

In [23]:
import numpy as np

arr = np.arange(6)

reshaped = arr.reshape(2, 3)
print(reshaped)

arr2 = np.arange(6)

arr2.resize(2, 4, refcheck=False)
print(arr2)

[[0 1 2]
 [3 4 5]]
[[0 1 2 3]
 [4 5 0 0]]


## 19. What is the difference between flatten() and ravel()?

| Feature | `flatten()` | `ravel()` |
|---|---|---|
| Returns | Always a copy | View when possible |
| Memory | More memory used | More efficient |
| Speed | Slightly slower | Faster |
| Affects original? | No | Yes, if a view |

In [ ]:
arr = np.array([[1, 2], [3, 4]])

flat = arr.flatten()
flat[0] = 99
print('After flatten modify, original:\n', arr)   # unaffected

rav = arr.ravel()
rav[0] = 99
print('After ravel modify, original:\n', arr)      # affected (view)

After flatten modify, original:
 [[1 2]
 [3 4]]
After ravel modify, original:
 [[99  2]
 [ 3  4]]


## 20. What is the difference between a view and a copy in NumPy?
- **View**: A new array object that **shares the same underlying memory/data buffer** as the original. Modifying a view modifies the original (and vice versa). Slicing returns a view.
- **Copy**: A completely **new, independent array** with its own memory. Modifying a copy does **not** affect the original. Fancy indexing, boolean indexing, and `.copy()` return copies.

Use `arr.base` to check if an array owns its data (`None` means it owns it, i.e. not a view), or use `np.shares_memory()`.

In [31]:
arr = np.arange(10)
view = arr[2:5]       # view
copy = arr[[2,3,4]].copy()   # explicit copy
np.shares_memory(arr, view)  # True

True

## 21. How do you concatenate multiple arrays in NumPy?
- **`np.concatenate()`**: Joins arrays along an existing axis.
- **`np.vstack()`**: Stacks arrays vertically (row-wise, along axis 0).
- **`np.hstack()`**: Stacks arrays horizontally (column-wise, along axis 1).
- **`np.stack()`**: Joins arrays along a **new** axis (increases dimensionality).

In [32]:
a = np.array([[1,2],[3,4]]); b = np.array([[5,6],[7,8]])
np.concatenate((a, b), axis=0)
np.vstack((a, b))
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## 22. How do you split an array into multiple sub-arrays?
- np.split() — equal parts (errors if not divisible)
- np.array_split() — allows uneven splits
- np.hsplit() — splits horizontally
- np.vsplit() — splits vertically

In [33]:
np.split(np.arange(9), 3)
np.array_split(np.arange(10), 3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

## 23. What are Universal Functions (ufuncs) in NumPy?
**Ufuncs** are functions that operate **element-wise** on ndarrays, support broadcasting, and are implemented in compiled C for speed. Examples: `np.add`, `np.subtract`, `np.multiply`, `np.sqrt`, `np.exp`, `np.sin`, `np.log`, `np.maximum`. They also support extra features like the `out` parameter (write result into an existing array) and reduction methods (`np.add.reduce`).

In [34]:
np.sqrt(np.array([1, 4, 9, 16]))   # [1, 2, 3, 4]

array([1., 2., 3., 4.])

## 24. What is the purpose of the axis parameter in NumPy functions?

The `axis` parameter tells NumPy **which dimension to operate along** when applying functions like `sum()`, `mean()`, `max()`, etc. Without `axis`, the function collapses the **entire** array into a single value. With `axis` specified, it collapses only along that dimension.

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
arr.sum()          # 21 (all elements)
arr.sum(axis=0)    # [5, 7, 9]
arr.sum(axis=1)    # [6, 15]

array([ 6, 15])

## 25. What is the difference between axis=0 and axis=1?
For a 2D array:
- **`axis=0`**: Operates **down the rows**, i.e. **column-wise** — collapses rows, producing one result per column.
- **`axis=1`**: Operates **across the columns**, i.e. **row-wise** — collapses columns, producing one result per row.

A helpful mnemonic: the axis number refers to which dimension **shrinks/disappears** in the output.

## 26. What is the difference between element-wise multiplication and matrix multiplication?
- **Element-wise multiplication (`*` or `np.multiply`)**: Multiplies corresponding elements; requires the same shape (or broadcastable shapes). Result has the same shape as inputs.
- **Matrix multiplication (`@`, `np.dot`, `np.matmul`)**: Performs true linear-algebra matrix multiplication (rows × columns, sum of products). Requires inner dimensions to match (`(m, n) x (n, p) -> (m, p)`).

In [36]:
a = np.array([[1,2],[3,4]]); b = np.array([[5,6],[7,8]])
a * b     # element-wise
a @ b     # matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('Element-wise:\n', a * b)
print('Matrix multiplication:\n', a @ b)

Element-wise:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]


## 27. What is the difference between np.dot(), @, and np.matmul()?

| Function | Behavior |
|---|---|
| `np.dot()` | 2D: matrix mult. 1D: dot product. N-D: sum-product over last/second-to-last axes |
| `@` | Same as `np.matmul()`; standard operator (PEP 465) |
| `np.matmul()` | Matrix mult.; treats `ndim > 2` as stacks of matrices (batched), unlike `dot()`. No scalar multiplication allowed |

## 28. How do you generate random numbers in NumPy, and what is the purpose of np.random.seed()?
NumPy's `random` module (legacy API) or the newer `Generator` API (`np.random.default_rng()`) can generate random numbers:
- `np.random.rand()` — uniform [0, 1)
- `np.random.randn()` — standard normal distribution
- `np.random.randint(low, high)` — random integers
- `np.random.choice()` — random sample from a given array

**`np.random.seed(n)`** initializes the pseudo-random number generator with a fixed starting point, making random sequences **reproducible** — essential for debugging and sharing results.

In [ ]:
np.random.seed(42)
print(np.random.rand(3))          # same output every run with seed 42
print(np.random.randint(1, 10, 5))

# Modern recommended API
rng = np.random.default_rng(seed=42)
print(rng.random(3))

[0.37454012 0.95071431 0.73199394]
[5 7 3 7 8]
[0.77395605 0.43887844 0.85859792]


## 29. How do you find unique values, counts, and frequencies in a NumPy array?
Use `np.unique()`, optionally with `return_counts=True` to get the frequency of each unique value.

In [38]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 1, 1])
vals, counts = np.unique(arr, return_counts=True)
freq = dict(zip(vals, counts))
arr

array([1, 2, 2, 3, 3, 3, 4, 1, 1])

## 30. What are the best practices for optimizing NumPy code performance?

- **Vectorize**: Avoid explicit Python `for` loops; use array operations and ufuncs instead.
- **Avoid unnecessary copies**: Prefer views (slicing) over copies when you don't need independent data; use in-place operations (`+=`, `out=` parameter) where appropriate.
- **Use appropriate dtypes**: Smaller dtypes (`float32` vs `float64`, `int8` vs `int64`) reduce memory and can speed up computation.
- **Leverage broadcasting** instead of manually tiling/repeating arrays.
- **Preallocate arrays** rather than growing them in a loop (e.g. avoid repeated `np.append()`/`np.concatenate()` in a loop).
- **Use built-in aggregation functions** (`np.sum`, `np.mean`, etc.) instead of manual loops.
- **Exploit contiguous memory layout** (`C` vs `F` order) for cache-friendly access patterns.
- **Use `numexpr`, `numba`, or Cython** for further speedups on very heavy numeric workloads.
- **Profile first** (`%timeit`, `cProfile`) to find real bottlenecks before optimizing.